# Generated by Django 4.2 on 2024-08-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('edad', models.IntegerField()),
                ('dni', models.IntegerField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tarea')),
            ],
        ),
    ]
